import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
// import ReactMarkdown from 'react-markdown/with-html';
import Markdown from 'markdown-to-jsx';
import './BlogPage.css';
import brand from './what-is-a-brand.md';

/* 
    TO DO:
        I NEED A WAY TO CALL FOR A PARTICULAR BLOG FROM SALESFORCE JUST IN CASE SOMEONE
        TRIES TO USE A DIRECT LINK GENERATED BY REACT ROUTER TO VIEW A BLOG.

        We have access to the HTML parser... need to figure out how to use that though.
        - We might be able to avoid the parsing for the title, and instead just grab the
        text in the h1 (ie. for the blog title)... or any other element.

        It seems like I might need to be logged into Salesforce to actually see the hosted
        img links??

        - Add blog wheel to single blogs
        - Check mobile -> blog not fetching from mobile -> it doesn't look like it can hit my server
*/
// const fetchBlogData = (blogId, func) => {
//     if(blogId){
//         fetch(`http://localhost:3000/test2/?${blogId}`)
//             .then(res => res.json())
//             .then(res => {
//                 if(res?.errorCode) throw new Error("Server Error: " + res?.errorCode);
//                 func(res);
//             })
//             .catch(err => {
//                 console.log(err);
//             })
//     }
// }
const localMd = (func) => {
    fetch(brand)
        .then(res => {
            return res.text();
        })
        .then(res => {
            func(res);
        })
}

const TestBlogPage = ({ routeProps }) => {
    const [ data, updateBlogData ] = useState("What");

    useEffect(() => {
        // window.scrollTo(0,0);
        // if(routeProps?.location?.state){
        //     const { blogData } = routeProps?.location?.state;
        //     updateBlogData(blogData);
        // } else {
        //     let idParse = window.location.pathname?.match(/\/\w{6,}\//);
        //     if(idParse?.[0]){
        //         idParse = idParse[0]?.match(/\w*/g);
        //         idParse = idParse.reduce((acc, cur) => {
        //             if(cur) acc = cur;
        //             return acc;
        //         }, null);
        //     }
        //     fetchBlogData(idParse, updateBlogData);
        // }
        localMd(updateBlogData);
    }, [routeProps]);
    
    return (
        <div className="blog-container">
            <Link to={"/blogs"}><button>All Blogs</button></Link>
            <div className="blog-inner-container">
                {/* <ReactMarkdown htmlParser={htmlToReactParser} allowDangerousHtml={true}>
                    { data }
                </ReactMarkdown> */}
                <Markdown>
                    {data}
                </Markdown>

            </div>
        </div>
    )
}

export default TestBlogPage;